#!/usr/bin/env ruby
require "africa_palindrome"

# Returns true for a palindrome, false otherwise.
lines = File.readlines("phrases.txt")
lines.each do |line|
  if line.palindrome?
    puts "#{line} is a palindrome."
  else
    puts "#{line} is not a palindrome."
  end
end

# text = File.readlines("phrases.txt")
# text.each do |line|
#   puts line
# end

palindromes = lines.select { |line| line.palindrome? }
p palindromes

