#!/usr/bin/env ruby
require "africa_palindrome"

# Returns true for a palindrome, false otherwise.
text = File.read("phrases.txt")
text.split("\n").each do |line|
  if line.palindrome?
    puts "#{line} is a palindrome."
  else
    puts "#{line} is not a palindrome."
  end
end

text = File.readlines("phrases.txt")
text.each do |line|
  puts line
end