source 'https://rubygems.org'

gem 'sinatra', '~> 2.0.0' # Sinatra is a DSL for quickly creating web applications in Ruby with minimal effort
gem 'rerun', '~> 0.11.0' # Restarts your app when the filesystem changes